#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Error: Illegal number of arguments"
    exit 0
fi

if [ -z "$1" ]; then
    echo "Error: Project name must not be empty string"
fi

PRJ_FILENAME="/root/workspace/$1"
mkdir -p $PRJ_FILENAME/src
cp /root/.template/CMakeLists.txt $PRJ_FILENAME/CMakeLists.txt
cp /root/.template/main.cpp $PRJ_FILENAME/src/main.cpp
sed -i "s/youbot_project_name/$1/g" $PRJ_FILENAME/CMakeLists.txt

echo "Project with name '$1' successfully created at $PRJ_FILENAME"
