#!/bin/bash

if [ "$#" -ne 1 ]; then
    echo "Illegal number of arguments. One argument with the project name is required."
    exit 0
fi

if [ -z "$1" ]; then
    echo "Project name must not be empty string."
    exit 0
fi

PRJ_FILENAME="/root/workspace/$1"

if [[ -d "$PRJ_FILENAME" ] && [ -f "$PRJ_FILENAME/CMakeLists.txt" ]]; then
    echo "Project with name $1 already exists."
    exit 0
fi

mkdir -p $PRJ_FILENAME/src
cp /root/.template/CMakeLists.txt $PRJ_FILENAME/CMakeLists.txt
cp /root/.template/main.cpp $PRJ_FILENAME/src/main.cpp
sed -i "s/youbot_project_name/$1/g" $PRJ_FILENAME/CMakeLists.txt

echo "Project with name '$1' successfully created at $PRJ_FILENAME"
